"""Candidate H-1B sponsoring companies.

`tier` is an approximate band based on published USCIS H-1B Employer Data Hub
rankings. It is a bucket, not an exact approval count -- pull exact numbers from
https://www.uscis.gov/tools/reports-and-studies/h-1b-employer-data-hub

`slugs` are candidate job-board tokens. probe_boards.py tests each one against
the public Greenhouse / Lever / Ashby / SmartRecruiters APIs and keeps whatever
actually resolves, so wrong guesses here are harmless.
"""

# (name, tier, industry, extra slug guesses beyond the auto-generated ones)
COMPANIES = [
    # ---- Tier 1: consistently among the largest H-1B sponsors ----
    ("Amazon",                  "Top 25 sponsor", "Cloud / E-commerce", []),
    ("Google",                  "Top 25 sponsor", "Big Tech", []),
    ("Microsoft",               "Top 25 sponsor", "Big Tech", []),
    ("Meta",                    "Top 25 sponsor", "Big Tech", ["facebook"]),
    ("Apple",                   "Top 25 sponsor", "Big Tech", []),
    ("Infosys",                 "Top 25 sponsor", "IT Services", []),
    ("Tata Consultancy Services","Top 25 sponsor","IT Services", ["tcs"]),
    ("Cognizant",               "Top 25 sponsor", "IT Services", []),
    ("Deloitte",                "Top 25 sponsor", "Consulting", []),
    ("Accenture",               "Top 25 sponsor", "Consulting", []),
    ("IBM",                     "Top 25 sponsor", "Enterprise Tech", []),
    ("Capgemini",               "Top 25 sponsor", "IT Services", []),
    ("HCLTech",                 "Top 25 sponsor", "IT Services", ["hcl"]),
    ("Wipro",                   "Top 25 sponsor", "IT Services", []),
    ("Tech Mahindra",           "Top 25 sponsor", "IT Services", ["techmahindra"]),
    ("LTIMindtree",             "Top 25 sponsor", "IT Services", ["ltimindtree"]),
    ("JPMorgan Chase",          "Top 25 sponsor", "Finance", ["jpmorgan", "jpmc"]),
    ("Intel",                   "Top 25 sponsor", "Semiconductors", []),
    ("Qualcomm",                "Top 25 sponsor", "Semiconductors", []),
    ("NVIDIA",                  "Top 25 sponsor", "Semiconductors / AI", []),
    ("Walmart",                 "Top 25 sponsor", "Retail / Tech", ["walmartlabs"]),
    ("Goldman Sachs",           "Top 25 sponsor", "Finance", ["goldmansachs"]),
    ("EY",                      "Top 25 sponsor", "Consulting", ["ernstyoung"]),
    ("PwC",                     "Top 25 sponsor", "Consulting", ["pwc"]),
    ("KPMG",                    "Top 25 sponsor", "Consulting", []),

    # ---- Large / very active sponsors ----
    ("Oracle",                  "Large sponsor", "Enterprise Tech", []),
    ("Salesforce",              "Large sponsor", "SaaS", []),
    ("Adobe",                   "Large sponsor", "Software", []),
    ("Cisco",                   "Large sponsor", "Networking", []),
    ("VMware",                  "Large sponsor", "Enterprise Tech", []),
    ("SAP",                     "Large sponsor", "Enterprise Tech", []),
    ("Uber",                    "Large sponsor", "Marketplace", []),
    ("Lyft",                    "Large sponsor", "Marketplace", []),
    ("LinkedIn",                "Large sponsor", "Big Tech", []),
    ("PayPal",                  "Large sponsor", "Fintech", []),
    ("eBay",                    "Large sponsor", "E-commerce", []),
    ("Intuit",                  "Large sponsor", "Fintech", []),
    ("Bloomberg",               "Large sponsor", "Finance / Data", []),
    ("Capital One",             "Large sponsor", "Finance", ["capitalone"]),
    ("American Express",        "Large sponsor", "Finance", ["americanexpress", "amex"]),
    ("Citi",                    "Large sponsor", "Finance", ["citigroup", "citibank"]),
    ("Morgan Stanley",          "Large sponsor", "Finance", ["morganstanley"]),
    ("Wells Fargo",             "Large sponsor", "Finance", ["wellsfargo"]),
    ("Bank of America",         "Large sponsor", "Finance", ["bankofamerica", "bofa"]),
    ("Visa",                    "Large sponsor", "Fintech", []),
    ("Mastercard",              "Large sponsor", "Fintech", []),
    ("Autodesk",                "Large sponsor", "Design / CAD Software", []),
    ("Texas Instruments",       "Large sponsor", "Semiconductors", ["texasinstruments"]),
    ("AMD",                     "Large sponsor", "Semiconductors", []),
    ("Micron Technology",       "Large sponsor", "Semiconductors", ["micron"]),
    ("Applied Materials",       "Large sponsor", "Semiconductors", ["appliedmaterials"]),
    ("Broadcom",                "Large sponsor", "Semiconductors", []),
    ("Analog Devices",          "Large sponsor", "Semiconductors", ["analogdevices"]),
    ("Synopsys",                "Large sponsor", "EDA", []),
    ("Cadence Design Systems",  "Large sponsor", "EDA", ["cadence"]),
    ("Dell Technologies",       "Large sponsor", "Hardware", ["dell"]),
    ("HP",                      "Large sponsor", "Hardware", ["hp", "hpinc"]),
    ("Hewlett Packard Enterprise","Large sponsor","Enterprise Tech", ["hpe"]),
    ("Tesla",                   "Large sponsor", "Automotive / AI", []),
    ("Rivian",                  "Large sponsor", "Automotive", []),
    ("Boeing",                  "Large sponsor", "Aerospace", []),
    ("Lockheed Martin",         "Large sponsor", "Aerospace", ["lockheedmartin"]),
    ("Northrop Grumman",        "Large sponsor", "Aerospace", ["northropgrumman"]),
    ("General Motors",          "Large sponsor", "Automotive", ["generalmotors", "gm"]),
    ("Ford Motor Company",      "Large sponsor", "Automotive", ["ford"]),
    ("Johnson & Johnson",       "Large sponsor", "Healthcare", ["jnj", "johnsonandjohnson"]),
    ("Pfizer",                  "Large sponsor", "Pharma", []),
    ("Merck",                   "Large sponsor", "Pharma", []),
    ("Eli Lilly",               "Large sponsor", "Pharma", ["elililly", "lilly"]),
    ("UnitedHealth Group",      "Large sponsor", "Healthcare", ["unitedhealthgroup", "optum"]),
    ("CVS Health",              "Large sponsor", "Healthcare", ["cvshealth", "cvs"]),
    ("Comcast",                 "Large sponsor", "Media / Telecom", []),
    ("Verizon",                 "Large sponsor", "Telecom", []),
    ("AT&T",                    "Large sponsor", "Telecom", ["att"]),
    ("T-Mobile",                "Large sponsor", "Telecom", ["tmobile"]),
    ("Charles Schwab",          "Large sponsor", "Finance", ["charlesschwab", "schwab"]),
    ("Fidelity Investments",    "Large sponsor", "Finance", ["fidelity", "fidelityinvestments"]),
    ("BlackRock",               "Large sponsor", "Finance", []),
    ("Nielsen",                 "Large sponsor", "Data / Analytics", []),
    ("ADP",                     "Large sponsor", "HR Tech", []),
    ("Cummins",                 "Large sponsor", "Industrial", []),
    ("Qualtrics",               "Large sponsor", "SaaS", []),
    ("ServiceNow",              "Large sponsor", "SaaS", []),
    ("Workday",                 "Large sponsor", "SaaS", []),
    ("Splunk",                  "Large sponsor", "Data / Observability", []),
    ("Palo Alto Networks",      "Large sponsor", "Security", ["paloaltonetworks"]),
    ("Juniper Networks",        "Large sponsor", "Networking", ["junipernetworks", "juniper"]),
    ("NetApp",                  "Large sponsor", "Storage", []),
    ("Nutanix",                 "Large sponsor", "Cloud Infra", []),
    ("Akamai",                  "Large sponsor", "CDN / Security", ["akamaitechnologies"]),
    ("Expedia Group",           "Large sponsor", "Travel Tech", ["expedia", "expediagroup"]),
    ("Booking.com",             "Large sponsor", "Travel Tech", ["booking", "bookingcom"]),
    ("Yahoo",                   "Large sponsor", "Media / Tech", []),
    ("Zoom",                    "Large sponsor", "Communications", ["zoomvideocommunications", "zoomus"]),
    ("Nordstrom",               "Large sponsor", "Retail / Tech", []),
    ("Target",                  "Large sponsor", "Retail / Tech", []),
    ("Costco",                  "Large sponsor", "Retail / Tech", ["costcowholesale"]),

    # ---- Active sponsors: high-growth tech, usually on public ATS boards ----
    ("Stripe",                  "Active sponsor", "Fintech", []),
    ("Databricks",              "Active sponsor", "Data / AI", []),
    ("Snowflake",               "Active sponsor", "Data Cloud", ["snowflakecomputing"]),
    ("OpenAI",                  "Active sponsor", "AI", []),
    ("Anthropic",               "Active sponsor", "AI", []),
    ("Scale AI",                "Active sponsor", "AI", ["scaleai", "scale"]),
    ("Figma",                   "Active sponsor", "Design Tools", []),
    ("Notion",                  "Active sponsor", "Productivity", ["notionhq", "notionlabs"]),
    ("Airtable",                "Active sponsor", "Productivity", []),
    ("Asana",                   "Active sponsor", "Productivity", []),
    ("Atlassian",               "Active sponsor", "Dev Tools", []),
    ("GitLab",                  "Active sponsor", "Dev Tools", []),
    ("HashiCorp",               "Active sponsor", "Dev Tools", []),
    ("Datadog",                 "Active sponsor", "Observability", []),
    ("MongoDB",                 "Active sponsor", "Databases", []),
    ("Elastic",                 "Active sponsor", "Search / Data", ["elasticsearch"]),
    ("Confluent",               "Active sponsor", "Data Streaming", []),
    ("Cloudflare",              "Active sponsor", "Infra / Security", []),
    ("Coinbase",                "Active sponsor", "Crypto", []),
    ("Robinhood",               "Active sponsor", "Fintech", []),
    ("Plaid",                   "Active sponsor", "Fintech", []),
    ("Brex",                    "Active sponsor", "Fintech", []),
    ("Ramp",                    "Active sponsor", "Fintech", []),
    ("Chime",                   "Active sponsor", "Fintech", []),
    ("Affirm",                  "Active sponsor", "Fintech", []),
    ("Block",                   "Active sponsor", "Fintech", ["square", "squareup"]),
    ("DoorDash",                "Active sponsor", "Marketplace", ["doordashusa"]),
    ("Instacart",               "Active sponsor", "Marketplace", ["maplebear"]),
    ("Airbnb",                  "Active sponsor", "Marketplace", []),
    ("Pinterest",               "Active sponsor", "Social", []),
    ("Reddit",                  "Active sponsor", "Social", []),
    ("Discord",                 "Active sponsor", "Social", []),
    ("Snap",                    "Active sponsor", "Social", ["snapchat", "snapinc"]),
    ("Spotify",                 "Active sponsor", "Media", []),
    ("Roblox",                  "Active sponsor", "Gaming", []),
    ("Unity",                   "Active sponsor", "Gaming", ["unitytechnologies"]),
    ("Electronic Arts",         "Active sponsor", "Gaming", ["ea", "electronicarts"]),
    ("Riot Games",              "Active sponsor", "Gaming", ["riotgames"]),
    ("Epic Games",              "Active sponsor", "Gaming", ["epicgames"]),
    ("Twilio",                  "Active sponsor", "Communications", []),
    ("Okta",                    "Active sponsor", "Security", []),
    ("CrowdStrike",             "Active sponsor", "Security", []),
    ("Zscaler",                 "Active sponsor", "Security", []),
    ("SentinelOne",             "Active sponsor", "Security", []),
    ("Rubrik",                  "Active sponsor", "Data Security", []),
    ("Samsara",                 "Active sponsor", "IoT", []),
    ("Verkada",                 "Active sponsor", "IoT / Security", []),
    ("Benchling",               "Active sponsor", "Bio Tech", []),
    ("Flexport",                "Active sponsor", "Logistics", []),
    ("Wayfair",                 "Active sponsor", "E-commerce", []),
    ("Chewy",                   "Active sponsor", "E-commerce", []),
    ("Etsy",                    "Active sponsor", "E-commerce", []),
    ("Shopify",                 "Active sponsor", "E-commerce", []),
    ("Yelp",                    "Active sponsor", "Local / Search", []),
    ("Zillow",                  "Active sponsor", "Real Estate Tech", ["zillowgroup"]),
    ("Redfin",                  "Active sponsor", "Real Estate Tech", []),
    ("Compass",                 "Active sponsor", "Real Estate Tech", ["urbancompass"]),
    ("Peloton",                 "Active sponsor", "Consumer Tech", ["pelotoncycle"]),
    ("Duolingo",                "Active sponsor", "EdTech", []),
    ("Coursera",                "Active sponsor", "EdTech", []),
    ("Udemy",                   "Active sponsor", "EdTech", []),
    ("Grammarly",               "Active sponsor", "AI / Productivity", []),
    ("Dropbox",                 "Active sponsor", "Cloud Storage", []),
    ("Box",                     "Active sponsor", "Cloud Storage", []),
    ("Slack",                   "Active sponsor", "Communications", []),
    ("Segment",                 "Active sponsor", "Data", []),
    ("Amplitude",               "Active sponsor", "Analytics", []),
    ("Sigma Computing",         "Active sponsor", "Analytics", ["sigmacomputing"]),
    ("dbt Labs",                "Active sponsor", "Data", ["dbtlabs"]),
    ("Vercel",                  "Active sponsor", "Dev Tools", []),
    ("Netlify",                 "Active sponsor", "Dev Tools", []),
    ("Postman",                 "Active sponsor", "Dev Tools", []),
    ("Sentry",                  "Active sponsor", "Dev Tools", ["getsentry"]),
    ("CircleCI",                "Active sponsor", "Dev Tools", []),
    ("Anduril Industries",      "Active sponsor", "Defense Tech", ["anduril"]),
    ("SpaceX",                  "Active sponsor", "Aerospace", []),
    ("Waymo",                   "Active sponsor", "Autonomous Vehicles", []),
    ("Cruise",                  "Active sponsor", "Autonomous Vehicles", ["getcruise"]),
    ("Zoox",                    "Active sponsor", "Autonomous Vehicles", []),
    ("Nuro",                    "Active sponsor", "Autonomous Vehicles", []),
    ("Applied Intuition",       "Active sponsor", "Autonomous Vehicles", ["appliedintuition"]),
    ("Two Sigma",               "Active sponsor", "Quant Finance", ["twosigma"]),
    ("Citadel",                 "Active sponsor", "Quant Finance", []),
    ("Jane Street",             "Active sponsor", "Quant Finance", ["janestreet"]),
    ("Hudson River Trading",    "Active sponsor", "Quant Finance", ["hudsonrivertrading", "hrt"]),
    ("Jump Trading",            "Active sponsor", "Quant Finance", ["jumptrading"]),
    ("DRW",                     "Active sponsor", "Quant Finance", []),
    ("IMC Trading",             "Active sponsor", "Quant Finance", ["imc", "imctrading"]),
    ("Optiver",                 "Active sponsor", "Quant Finance", []),
    ("Point72",                 "Active sponsor", "Quant Finance", []),
    ("Millennium",              "Active sponsor", "Quant Finance", ["mlp", "millenniummanagement"]),
    ("Belvedere Trading",       "Active sponsor", "Quant Finance", ["belvederetrading"]),
    ("Akuna Capital",           "Active sponsor", "Quant Finance", ["akunacapital"]),
    ("SIG",                     "Active sponsor", "Quant Finance", ["susquehanna", "sig"]),

    # ---- Expansion: AI / ML labs and infrastructure ----
    ("Perplexity AI",           "Active sponsor", "AI", ["perplexityai", "perplexity"]),
    ("Glean",                   "Active sponsor", "AI / Search", ["gleanwork"]),
    ("Together AI",             "Active sponsor", "AI Infra", ["togetherai", "together"]),
    ("Fireworks AI",            "Active sponsor", "AI Infra", ["fireworksai"]),
    ("Baseten",                 "Active sponsor", "AI Infra", []),
    ("Modal Labs",              "Active sponsor", "AI Infra", ["modal", "modallabs"]),
    ("Replicate",               "Active sponsor", "AI Infra", []),
    ("Pinecone",                "Active sponsor", "Vector DB", []),
    ("Weaviate",                "Active sponsor", "Vector DB", []),
    ("LangChain",               "Active sponsor", "AI Tooling", []),
    ("Weights & Biases",        "Active sponsor", "ML Tooling", ["weightsandbiases", "wandb"]),
    ("Hugging Face",            "Active sponsor", "AI", ["huggingface"]),
    ("Cerebras Systems",        "Active sponsor", "AI Hardware", ["cerebras"]),
    ("Groq",                    "Active sponsor", "AI Hardware", []),
    ("SambaNova Systems",       "Active sponsor", "AI Hardware", ["sambanova"]),
    ("Lambda",                  "Active sponsor", "AI Cloud", ["lambdalabs"]),
    ("Harvey",                  "Active sponsor", "Legal AI", ["harveyai"]),
    ("Sierra",                  "Active sponsor", "AI", ["sierraai"]),
    ("Abridge",                 "Active sponsor", "Health AI", []),
    ("Palantir Technologies",   "Active sponsor", "Data / Defense", ["palantir"]),

    # ---- Expansion: developer tools & data infrastructure ----
    ("Temporal Technologies",   "Active sponsor", "Dev Tools", ["temporal", "temporalio"]),
    ("Grafana Labs",            "Active sponsor", "Observability", ["grafanalabs", "grafana"]),
    ("Chronosphere",            "Active sponsor", "Observability", []),
    ("Honeycomb",               "Active sponsor", "Observability", ["honeycombio"]),
    ("Cribl",                   "Active sponsor", "Data / Observability", []),
    ("Fivetran",                "Active sponsor", "Data", []),
    ("Airbyte",                 "Active sponsor", "Data", []),
    ("Hex Technologies",        "Active sponsor", "Analytics", ["hex", "hextechnologies"]),
    ("Retool",                  "Active sponsor", "Dev Tools", []),
    ("Linear",                  "Active sponsor", "Dev Tools", []),
    ("Supabase",                "Active sponsor", "Databases", []),
    ("Neon",                    "Active sponsor", "Databases", ["neondatabase"]),
    ("Cockroach Labs",          "Active sponsor", "Databases", ["cockroachlabs"]),
    ("SingleStore",             "Active sponsor", "Databases", []),
    ("Redis",                   "Active sponsor", "Databases", ["redislabs"]),
    ("ClickHouse",              "Active sponsor", "Databases", []),
    ("Materialize",             "Active sponsor", "Data", []),
    ("Astronomer",              "Active sponsor", "Data", []),
    ("Render",                  "Active sponsor", "Cloud", ["renderco"]),
    ("Railway",                 "Active sponsor", "Cloud", ["railwayapp"]),
    ("DigitalOcean",            "Active sponsor", "Cloud", []),
    ("Fastly",                  "Active sponsor", "CDN", []),
    ("PagerDuty",               "Active sponsor", "Ops", []),
    ("LaunchDarkly",            "Active sponsor", "Dev Tools", []),
    ("Docker",                  "Active sponsor", "Dev Tools", []),

    # ---- Expansion: security ----
    ("Wiz",                     "Active sponsor", "Security", ["wizio"]),
    ("Snyk",                    "Active sponsor", "Security", []),
    ("Orca Security",           "Active sponsor", "Security", ["orcasecurity"]),
    ("Abnormal Security",       "Active sponsor", "Security", ["abnormalsecurity"]),
    ("Tailscale",               "Active sponsor", "Networking", []),
    ("1Password",               "Active sponsor", "Security", ["agilebits", "1password"]),
    ("Vanta",                   "Active sponsor", "Compliance", []),
    ("Drata",                   "Active sponsor", "Compliance", []),
    ("Chainguard",              "Active sponsor", "Security", []),
    ("Semgrep",                 "Active sponsor", "Security", []),
    ("HackerOne",               "Active sponsor", "Security", []),
    ("Netskope",                "Active sponsor", "Security", []),
    ("Arctic Wolf",             "Active sponsor", "Security", ["arcticwolf"]),
    ("Tenable",                 "Active sponsor", "Security", []),
    ("Rapid7",                  "Active sponsor", "Security", []),

    # ---- Expansion: fintech ----
    ("Marqeta",                 "Active sponsor", "Fintech", []),
    ("Modern Treasury",         "Active sponsor", "Fintech", ["moderntreasury"]),
    ("Mercury",                 "Active sponsor", "Fintech", ["mercurytechnologies"]),
    ("Toast",                   "Active sponsor", "Fintech", ["toasttab"]),
    ("Gusto",                   "Active sponsor", "HR Tech", []),
    ("Rippling",                "Active sponsor", "HR Tech", []),
    ("Deel",                    "Active sponsor", "HR Tech", []),
    ("Carta",                   "Active sponsor", "Fintech", []),
    ("Addepar",                 "Active sponsor", "Fintech", []),
    ("Betterment",              "Active sponsor", "Fintech", []),
    ("Wealthfront",             "Active sponsor", "Fintech", []),
    ("SoFi",                    "Active sponsor", "Fintech", ["sofi"]),
    ("Remitly",                 "Active sponsor", "Fintech", []),
    ("Wise",                    "Active sponsor", "Fintech", ["transferwise"]),
    ("Navan",                   "Active sponsor", "Travel Tech", ["tripactions"]),
    ("Bill.com",                "Active sponsor", "Fintech", ["billcom", "bill"]),
    ("Nasdaq",                  "Large sponsor",  "Finance", []),
    ("CME Group",               "Large sponsor",  "Finance", ["cmegroup"]),
    ("S&P Global",              "Large sponsor",  "Finance / Data", ["spglobal"]),
    ("Moody's",                 "Large sponsor",  "Finance / Data", ["moodys"]),
    ("MSCI",                    "Large sponsor",  "Finance / Data", []),
    ("FactSet",                 "Large sponsor",  "Finance / Data", []),
    ("Morningstar",             "Large sponsor",  "Finance / Data", []),
    ("Fiserv",                  "Large sponsor",  "Fintech", []),
    ("Discover Financial",      "Large sponsor",  "Finance", ["discover"]),
    ("Ally Financial",          "Large sponsor",  "Finance", ["ally"]),

    # ---- Expansion: quant / trading ----
    ("Virtu Financial",         "Active sponsor", "Quant Finance", ["virtu"]),
    ("Tower Research Capital",  "Active sponsor", "Quant Finance", ["towerresearch", "tower"]),
    ("XTX Markets",             "Active sponsor", "Quant Finance", ["xtxmarkets"]),
    ("Squarepoint Capital",     "Active sponsor", "Quant Finance", ["squarepoint"]),
    ("Balyasny Asset Management","Active sponsor","Quant Finance", ["balyasny", "bamfunds"]),
    ("Schonfeld",               "Active sponsor", "Quant Finance", []),
    ("Old Mission Capital",     "Active sponsor", "Quant Finance", ["oldmission"]),
    ("Wolverine Trading",       "Active sponsor", "Quant Finance", ["wolverinetrading"]),
    ("Peak6",                   "Active sponsor", "Quant Finance", []),
    ("Five Rings",              "Active sponsor", "Quant Finance", ["fiverings"]),
    ("Headlands Technologies",  "Active sponsor", "Quant Finance", ["headlands"]),
    ("Quantlab",                "Active sponsor", "Quant Finance", []),
    ("AQR Capital Management",  "Active sponsor", "Quant Finance", ["aqr"]),
    ("Bridgewater Associates",  "Active sponsor", "Quant Finance", ["bridgewater"]),
    ("D. E. Shaw",              "Active sponsor", "Quant Finance", ["deshaw"]),
    ("Chicago Trading Company", "Active sponsor", "Quant Finance", ["chicagotrading", "ctc"]),

    # ---- Expansion: health / bio tech ----
    ("Tempus AI",               "Active sponsor", "Health AI", ["tempus"]),
    ("Recursion",               "Active sponsor", "Biotech", ["recursionpharmaceuticals"]),
    ("insitro",                 "Active sponsor", "Biotech", []),
    ("Oscar Health",            "Active sponsor", "Healthtech", ["oscarhealth"]),
    ("Included Health",         "Active sponsor", "Healthtech", ["includedhealth"]),
    ("Hinge Health",            "Active sponsor", "Healthtech", ["hingehealth"]),
    ("Cedar",                   "Active sponsor", "Healthtech", ["cedarcares"]),
    ("Komodo Health",           "Active sponsor", "Health Data", ["komodohealth"]),
    ("Natera",                  "Active sponsor", "Biotech", []),
    ("Guardant Health",         "Active sponsor", "Biotech", ["guardanthealth"]),
    ("10x Genomics",            "Active sponsor", "Biotech", ["10xgenomics"]),
    ("Illumina",                "Large sponsor",  "Biotech", []),
    ("Moderna",                 "Large sponsor",  "Pharma", []),
    ("Regeneron",               "Large sponsor",  "Pharma", []),
    ("Amgen",                   "Large sponsor",  "Pharma", []),
    ("Gilead Sciences",         "Large sponsor",  "Pharma", ["gilead"]),
    ("Biogen",                  "Large sponsor",  "Pharma", []),
    ("Vertex Pharmaceuticals",  "Large sponsor",  "Pharma", ["vertexpharmaceuticals"]),
    ("AbbVie",                  "Large sponsor",  "Pharma", []),
    ("Bristol Myers Squibb",    "Large sponsor",  "Pharma", ["bristolmyerssquibb", "bms"]),

    # ---- Expansion: semiconductors & hardware ----
    ("Marvell Technology",      "Large sponsor",  "Semiconductors", ["marvell"]),
    ("Astera Labs",             "Active sponsor", "Semiconductors", ["asteralabs"]),
    ("Tenstorrent",             "Active sponsor", "AI Hardware", []),
    ("SiFive",                  "Active sponsor", "Semiconductors", []),
    ("Arm",                     "Large sponsor",  "Semiconductors", ["armltd", "arm"]),
    ("GlobalFoundries",         "Large sponsor",  "Semiconductors", []),
    ("onsemi",                  "Large sponsor",  "Semiconductors", ["onsemiconductor"]),
    ("NXP Semiconductors",      "Large sponsor",  "Semiconductors", ["nxp"]),
    ("Skyworks Solutions",      "Large sponsor",  "Semiconductors", ["skyworks"]),
    ("Qorvo",                   "Large sponsor",  "Semiconductors", []),
    ("Lattice Semiconductor",   "Active sponsor", "Semiconductors", ["latticesemiconductor"]),
    ("Ambarella",               "Active sponsor", "Semiconductors", []),
    ("Keysight Technologies",   "Large sponsor",  "Test & Measurement", ["keysight"]),
    ("Teradyne",                "Large sponsor",  "Semiconductors", []),
    ("KLA",                     "Large sponsor",  "Semiconductors", ["klatencor"]),
    ("Lam Research",            "Large sponsor",  "Semiconductors", ["lamresearch"]),
    ("ASML",                    "Large sponsor",  "Semiconductors", []),

    # ---- Expansion: aerospace, defense, autonomy ----
    ("Rocket Lab",              "Active sponsor", "Aerospace", ["rocketlab", "rocketlabusa"]),
    ("Relativity Space",        "Active sponsor", "Aerospace", ["relativityspace"]),
    ("Firefly Aerospace",       "Active sponsor", "Aerospace", ["fireflyaerospace"]),
    ("Blue Origin",             "Active sponsor", "Aerospace", ["blueorigin"]),
    ("Planet Labs",             "Active sponsor", "Space Data", ["planetlabs", "planet"]),
    ("Sierra Space",            "Active sponsor", "Aerospace", ["sierraspace"]),
    ("Axiom Space",             "Active sponsor", "Aerospace", ["axiomspace"]),
    ("Joby Aviation",           "Active sponsor", "Aviation", ["jobyaviation", "joby"]),
    ("Archer Aviation",         "Active sponsor", "Aviation", ["archeraviation", "archer"]),
    ("Shield AI",               "Active sponsor", "Defense Tech", ["shieldai"]),
    ("Skydio",                  "Active sponsor", "Drones", []),
    ("Saronic",                 "Active sponsor", "Defense Tech", []),
    ("Figure AI",               "Active sponsor", "Robotics", ["figureai", "figure"]),
    ("Lucid Motors",            "Active sponsor", "Automotive", ["lucidmotors"]),
    ("Aurora Innovation",       "Active sponsor", "Autonomous Vehicles", ["aurora"]),
    ("Motional",                "Active sponsor", "Autonomous Vehicles", []),
    ("Wayve",                   "Active sponsor", "Autonomous Vehicles", []),

    # ---- Expansion: consumer, marketplace, SaaS ----
    ("Faire",                   "Active sponsor", "Marketplace", ["faire", "faireinc"]),
    ("Whatnot",                 "Active sponsor", "Marketplace", []),
    ("StockX",                  "Active sponsor", "Marketplace", []),
    ("Turo",                    "Active sponsor", "Marketplace", []),
    ("Hopper",                  "Active sponsor", "Travel Tech", []),
    ("TripAdvisor",             "Active sponsor", "Travel Tech", ["tripadvisor"]),
    ("Gopuff",                  "Active sponsor", "Delivery", ["gopuff"]),
    ("Sweetgreen",              "Active sponsor", "Food Tech", []),
    ("Warby Parker",            "Active sponsor", "Retail", ["warbyparker"]),
    ("HubSpot",                 "Active sponsor", "SaaS", []),
    ("Klaviyo",                 "Active sponsor", "SaaS", []),
    ("Braze",                   "Active sponsor", "SaaS", []),
    ("Attentive",               "Active sponsor", "SaaS", ["attentivemobile"]),
    ("Zendesk",                 "Active sponsor", "SaaS", []),
    ("Freshworks",              "Active sponsor", "SaaS", []),
    ("Smartsheet",              "Active sponsor", "SaaS", []),
    ("Miro",                    "Active sponsor", "SaaS", ["mirohq"]),
    ("Canva",                   "Active sponsor", "Design Tools", []),
    ("Zapier",                  "Active sponsor", "Automation", []),
    ("Calendly",                "Active sponsor", "SaaS", []),
    ("Expensify",               "Active sponsor", "Fintech", []),
    ("Sprinklr",                "Active sponsor", "SaaS", []),
    ("Twitch",                  "Active sponsor", "Media", []),
    ("Niantic",                 "Active sponsor", "Gaming", ["nianticlabs"]),
    ("Scopely",                 "Active sponsor", "Gaming", []),
    ("AppLovin",                "Active sponsor", "AdTech", []),
    ("The Trade Desk",          "Active sponsor", "AdTech", ["thetradedesk"]),
    ("Netflix",                 "Large sponsor",  "Media", []),
    ("Roku",                    "Active sponsor", "Media", []),
    ("Sonos",                   "Active sponsor", "Consumer Hardware", []),
    ("Life360",                 "Active sponsor", "Consumer Tech", []),
    ("Strava",                  "Active sponsor", "Consumer Tech", []),
    ("Robinhood Markets",       "Active sponsor", "Fintech", ["robinhoodmarkets"]),

    # ---- Expansion: IT services (frequent H-1B filers) ----
    ("Genpact",                 "Large sponsor",  "IT Services", []),
    ("Mphasis",                 "Large sponsor",  "IT Services", []),
    ("Persistent Systems",      "Large sponsor",  "IT Services", ["persistentsystems", "persistent"]),
    ("Hexaware Technologies",   "Large sponsor",  "IT Services", ["hexaware"]),
    ("Coforge",                 "Large sponsor",  "IT Services", []),
    ("Virtusa",                 "Large sponsor",  "IT Services", []),
    ("UST",                     "Large sponsor",  "IT Services", ["ustglobal"]),
    ("Birlasoft",               "Large sponsor",  "IT Services", []),
    ("Cyient",                  "Large sponsor",  "IT Services", []),
    ("Zensar Technologies",     "Large sponsor",  "IT Services", ["zensar"]),
    ("EPAM Systems",            "Large sponsor",  "IT Services", ["epam"]),
    ("Globant",                 "Large sponsor",  "IT Services", []),
    ("Thoughtworks",            "Large sponsor",  "IT Services", []),
    ("Slalom",                  "Large sponsor",  "Consulting", []),
    ("Booz Allen Hamilton",     "Large sponsor",  "Consulting", ["boozallenhamilton", "bah"]),
    ("Leidos",                  "Large sponsor",  "Defense IT", []),
    ("SAIC",                    "Large sponsor",  "Defense IT", []),
    ("CACI",                    "Large sponsor",  "Defense IT", ["caci"]),
    ("MITRE",                   "Large sponsor",  "Research", []),
    ("RTX",                     "Large sponsor",  "Aerospace", ["raytheon", "rtx"]),
    ("L3Harris",                "Large sponsor",  "Aerospace", ["l3harris"]),
    ("General Dynamics",        "Large sponsor",  "Aerospace", ["generaldynamics"]),
    ("Honeywell",               "Large sponsor",  "Industrial", []),
    ("Emerson Electric",        "Large sponsor",  "Industrial", ["emerson"]),
    ("Rockwell Automation",     "Large sponsor",  "Industrial", ["rockwellautomation"]),
    ("John Deere",              "Large sponsor",  "Industrial", ["deere", "johndeere"]),
    ("Caterpillar",             "Large sponsor",  "Industrial", []),
    ("3M",                      "Large sponsor",  "Industrial", ["3m", "mmm"]),
    ("General Electric",        "Large sponsor",  "Industrial", ["generalelectric", "ge"]),
    ("Siemens",                 "Large sponsor",  "Industrial", []),
    ("Bosch",                   "Large sponsor",  "Industrial", ["boschgroup"]),
    ("Nike",                    "Large sponsor",  "Retail / Tech", []),
    ("Starbucks",               "Large sponsor",  "Retail / Tech", []),
    ("FedEx",                   "Large sponsor",  "Logistics", []),
    ("UPS",                     "Large sponsor",  "Logistics", []),
    ("Delta Air Lines",         "Large sponsor",  "Airlines", ["delta"]),
    ("United Airlines",         "Large sponsor",  "Airlines", ["united", "unitedairlines"]),
    ("American Airlines",       "Large sponsor",  "Airlines", ["americanairlines", "aa"]),
    ("Marriott International",  "Large sponsor",  "Hospitality", ["marriott"]),
    ("Kaiser Permanente",       "Large sponsor",  "Healthcare", ["kaiserpermanente"]),
    ("Humana",                  "Large sponsor",  "Healthcare", []),
    ("Elevance Health",         "Large sponsor",  "Healthcare", ["elevancehealth", "anthem"]),
    ("Cigna",                   "Large sponsor",  "Healthcare", ["thecignagroup"]),
    ("McKesson",                "Large sponsor",  "Healthcare", []),
    ("Liberty Mutual",          "Large sponsor",  "Insurance", ["libertymutual"]),
    ("Progressive",             "Large sponsor",  "Insurance", []),
    ("Allstate",                "Large sponsor",  "Insurance", []),
    ("State Farm",              "Large sponsor",  "Insurance", ["statefarm"]),
    ("USAA",                    "Large sponsor",  "Insurance", []),
    ("Travelers",               "Large sponsor",  "Insurance", []),
    ("Nationwide",              "Large sponsor",  "Insurance", []),
    ("PNC Financial Services",  "Large sponsor",  "Finance", ["pnc"]),
    ("U.S. Bank",               "Large sponsor",  "Finance", ["usbank"]),
    ("Truist",                  "Large sponsor",  "Finance", []),
    ("Synchrony",               "Large sponsor",  "Finance", ["synchronyfinancial"]),
    ("Northwestern Mutual",     "Large sponsor",  "Finance", ["northwesternmutual"]),
]


# Workday tenants to probe: (name, tier, industry, tenant, host-hint, site-hint).
# probe_boards.py tries several host/site combinations, so hints can be rough.
WORKDAY_CANDIDATES = [
    ("NVIDIA", "Top 25 sponsor", "Semiconductors / AI", "nvidia", "wd5", "NVIDIAExternalCareerSite"),
    ("Adobe", "Large sponsor", "Software", "adobe", "wd5", "external_experienced"),
    ("Salesforce", "Large sponsor", "SaaS", "salesforce", "wd12", "External_Career_Site"),
    ("PayPal", "Large sponsor", "Fintech", "paypal", "wd1", "jobs"),
    ("eBay", "Large sponsor", "E-commerce", "ebay", "wd5", "apply"),
    ("Workday", "Large sponsor", "SaaS", "workday", "wd5", "Workday"),
    ("Target", "Large sponsor", "Retail / Tech", "target", "wd5", "targetcareers"),
    ("Comcast", "Large sponsor", "Media / Telecom", "comcast", "wd5", "Comcast_Careers"),
    ("T-Mobile", "Large sponsor", "Telecom", "tmobile", "wd1", "External"),
    ("Micron Technology", "Large sponsor", "Semiconductors", "micron", "wd1", "External"),
    ("Applied Materials", "Large sponsor", "Semiconductors", "amat", "wd1", "External"),
    ("Analog Devices", "Large sponsor", "Semiconductors", "analogdevices", "wd1", "External"),
    ("Cadence Design Systems", "Large sponsor", "EDA", "cadence", "wd1", "External_Careers"),
    ("Broadcom", "Large sponsor", "Semiconductors", "broadcom", "wd1", "External_Career"),
    ("Capital One", "Large sponsor", "Finance", "capitalone", "wd12", "Capital_One"),
    ("Mastercard", "Large sponsor", "Fintech", "mastercard", "wd1", "CorporateCareers"),
    ("Visa", "Large sponsor", "Fintech", "visa", "wd5", "Visa"),
    ("Autodesk", "Large sponsor", "Design / CAD Software", "autodesk", "wd1", "Ext"),
    ("Intel", "Top 25 sponsor", "Semiconductors", "intel", "wd1", "External"),
    ("Arctic Wolf", "Active sponsor", "Security", "arcticwolf", "wd1", "External"),
    ("Axiom Space", "Active sponsor", "Aerospace", "axiomspace", "wd5", "External_Career_Site"),
    ("Sprinklr", "Active sponsor", "SaaS", "sprinklr", "wd1", "Careers"),
    ("BlackRock", "Large sponsor", "Finance", "blackrock", "wd1", "BlackRock_Professional"),
    ("Boeing", "Large sponsor", "Aerospace", "boeing", "wd1", "EXTERNAL_CAREERS"),
    ("Northrop Grumman", "Large sponsor", "Aerospace", "ngc", "wd1", "Northrop_Grumman_External_Site"),
    ("Pfizer", "Large sponsor", "Pharma", "pfizer", "wd1", "PfizerCareers"),
    ("Merck", "Large sponsor", "Pharma", "msd", "wd5", "SearchJobs"),
    ("CVS Health", "Large sponsor", "Healthcare", "cvshealth", "wd1", "CVS_Health_Careers"),
    ("CrowdStrike", "Active sponsor", "Security", "crowdstrike", "wd5", "crowdstrikecareers"),
    ("Zillow", "Active sponsor", "Real Estate Tech", "zillow", "wd5", "Zillow_Group_External"),
    ("Etsy", "Active sponsor", "E-commerce", "etsy", "wd5", "Etsy_Careers"),
    ("Sony", "Active sponsor", "Media / Electronics", "sonyglobal", "wd1", "SonyGlobalCareers"),
    # --- new candidates ---
    ("Intuit", "Large sponsor", "Fintech", "intuit", "wd1", "IntuitCareers"),
    ("Dell Technologies", "Large sponsor", "Hardware", "dell", "wd1", "External"),
    ("Hewlett Packard Enterprise", "Large sponsor", "Enterprise Tech", "hpe", "wd5", "Jobsathpe-External"),
    ("HP", "Large sponsor", "Hardware", "hp", "wd5", "ExternalCareerSite"),
    ("Nordstrom", "Large sponsor", "Retail / Tech", "nordstrom", "wd5", "nordstrom_careers"),
    ("Expedia Group", "Large sponsor", "Travel Tech", "expedia", "wd5", "search"),
    ("NetApp", "Large sponsor", "Storage", "netapp", "wd5", "ncareers"),
    ("Nutanix", "Large sponsor", "Cloud Infra", "nutanix", "wd1", "Nutanix"),
    ("Splunk", "Large sponsor", "Data / Observability", "splunk", "wd1", "splunk_careers"),
    ("Palo Alto Networks", "Large sponsor", "Security", "paloaltonetworks", "wd1", "PaloAltoNetworks"),
    ("Juniper Networks", "Large sponsor", "Networking", "juniper", "wd5", "Juniper"),
    ("Akamai", "Large sponsor", "CDN / Security", "akamai", "wd1", "Akamai_Careers"),
    ("Yahoo", "Large sponsor", "Media / Tech", "yahoo", "wd1", "Careers"),
    ("Synopsys", "Large sponsor", "EDA", "synopsys", "wd1", "Careers"),
    ("Texas Instruments", "Large sponsor", "Semiconductors", "ti", "wd1", "External"),
    ("AMD", "Large sponsor", "Semiconductors", "amd", "wd1", "External"),
    ("Marvell Technology", "Large sponsor", "Semiconductors", "marvell", "wd1", "MarvellCareers"),
    ("Keysight Technologies", "Large sponsor", "Test & Measurement", "keysight", "wd1", "External"),
    ("Teradyne", "Large sponsor", "Semiconductors", "teradyne", "wd1", "Teradyne"),
    ("KLA", "Large sponsor", "Semiconductors", "kla", "wd1", "Search"),
    ("Lam Research", "Large sponsor", "Semiconductors", "lamresearch", "wd1", "External"),
    ("GlobalFoundries", "Large sponsor", "Semiconductors", "globalfoundries", "wd1", "External"),
    ("NXP Semiconductors", "Large sponsor", "Semiconductors", "nxp", "wd3", "careers"),
    ("onsemi", "Large sponsor", "Semiconductors", "onsemi", "wd5", "ONSEMI"),
    ("Qorvo", "Large sponsor", "Semiconductors", "qorvo", "wd1", "External"),
    ("Skyworks Solutions", "Large sponsor", "Semiconductors", "skyworks", "wd1", "Skyworks"),
    ("ASML", "Large sponsor", "Semiconductors", "asml", "wd3", "ASML_Careers"),
    ("Verizon", "Large sponsor", "Telecom", "verizon", "wd12", "verizon"),
    ("Charles Schwab", "Large sponsor", "Finance", "schwabjobs", "wd5", "Careers"),
    ("Fidelity Investments", "Large sponsor", "Finance", "fidelity", "wd1", "FidelityCareers"),
    ("Morgan Stanley", "Large sponsor", "Finance", "ms", "wd5", "External"),
    ("American Express", "Large sponsor", "Finance", "aexp", "wd1", "AmericanExpress"),
    ("Wells Fargo", "Large sponsor", "Finance", "wellsfargojobs", "wd12", "WellsFargoJobs"),
    ("PNC Financial Services", "Large sponsor", "Finance", "pnc", "wd1", "External"),
    ("U.S. Bank", "Large sponsor", "Finance", "usbank", "wd12", "USBank_Careers"),
    ("Truist", "Large sponsor", "Finance", "truist", "wd1", "Truist_Careers"),
    ("Discover Financial", "Large sponsor", "Finance", "discover", "wd5", "Discover"),
    ("Synchrony", "Large sponsor", "Finance", "synchrony", "wd1", "Synchrony_Careers"),
    ("Ally Financial", "Large sponsor", "Finance", "ally", "wd1", "Ally_Careers"),
    ("Nasdaq", "Large sponsor", "Finance", "nasdaq", "wd1", "Nasdaq_External"),
    ("S&P Global", "Large sponsor", "Finance / Data", "spgi", "wd5", "SPGI_Careers"),
    ("Moody's", "Large sponsor", "Finance / Data", "moodys", "wd5", "Moodys_Careers"),
    ("MSCI", "Large sponsor", "Finance / Data", "msci", "wd1", "MSCI"),
    ("Fiserv", "Large sponsor", "Fintech", "fiserv", "wd5", "Fiserv"),
    ("Liberty Mutual", "Large sponsor", "Insurance", "libertymutual", "wd5", "LMCareers"),
    ("Progressive", "Large sponsor", "Insurance", "progressive", "wd5", "External"),
    ("Allstate", "Large sponsor", "Insurance", "allstate", "wd1", "Allstate_Careers"),
    ("USAA", "Large sponsor", "Insurance", "usaa", "wd1", "usaajobs"),
    ("Travelers", "Large sponsor", "Insurance", "travelers", "wd5", "External"),
    ("Nationwide", "Large sponsor", "Insurance", "nationwide", "wd1", "Nationwide_External"),
    ("Humana", "Large sponsor", "Healthcare", "humana", "wd5", "Humana_External"),
    ("Elevance Health", "Large sponsor", "Healthcare", "elevancehealth", "wd1", "EHCareers"),
    ("Cigna", "Large sponsor", "Healthcare", "cigna", "wd5", "cigna"),
    ("McKesson", "Large sponsor", "Healthcare", "mckesson", "wd5", "External_Careers"),
    ("Kaiser Permanente", "Large sponsor", "Healthcare", "kaiser", "wd5", "KP_Careers"),
    ("UnitedHealth Group", "Large sponsor", "Healthcare", "unitedhealthgroup", "wd1", "External"),
    ("Johnson & Johnson", "Large sponsor", "Healthcare", "jnj", "wd5", "JNJ_Careers"),
    ("Eli Lilly", "Large sponsor", "Pharma", "lilly", "wd5", "LLY"),
    ("Moderna", "Large sponsor", "Pharma", "moderna", "wd1", "M_EXT"),
    ("Regeneron", "Large sponsor", "Pharma", "regeneron", "wd1", "Regeneron_Careers"),
    ("Amgen", "Large sponsor", "Pharma", "amgen", "wd1", "Amgen_Careers"),
    ("Gilead Sciences", "Large sponsor", "Pharma", "gilead", "wd1", "gileadcareers"),
    ("Biogen", "Large sponsor", "Pharma", "biogen", "wd1", "Biogen_Careers"),
    ("AbbVie", "Large sponsor", "Pharma", "abbvie", "wd5", "abbviecareers"),
    ("Bristol Myers Squibb", "Large sponsor", "Pharma", "bmsah", "wd5", "BMS"),
    ("Illumina", "Large sponsor", "Biotech", "illumina", "wd1", "illumina_careers"),
    ("General Motors", "Large sponsor", "Automotive", "gm", "wd5", "Careers_GM"),
    ("Ford Motor Company", "Large sponsor", "Automotive", "ford", "wd1", "Ford_Careers"),
    ("Rivian", "Large sponsor", "Automotive", "rivian", "wd12", "Rivian"),
    ("Lucid Motors", "Active sponsor", "Automotive", "lucidmotors", "wd12", "Lucid_Careers"),
    ("RTX", "Large sponsor", "Aerospace", "rtx", "wd5", "REC_RTX"),
    ("L3Harris", "Large sponsor", "Aerospace", "l3harris", "wd1", "L3Harris_External"),
    ("General Dynamics", "Large sponsor", "Aerospace", "gd", "wd1", "External"),
    ("Lockheed Martin", "Top 25 sponsor", "Aerospace", "lockheedmartin", "wd1", "External"),
    ("Leidos", "Large sponsor", "Defense IT", "leidos", "wd5", "External"),
    ("SAIC", "Large sponsor", "Defense IT", "saic", "wd1", "External"),
    ("CACI", "Large sponsor", "Defense IT", "caci", "wd1", "External"),
    ("Booz Allen Hamilton", "Large sponsor", "Consulting", "bah", "wd1", "BAH_Jobs"),
    ("Honeywell", "Large sponsor", "Industrial", "honeywell", "wd1", "External"),
    ("Emerson Electric", "Large sponsor", "Industrial", "emerson", "wd1", "Emerson_Careers"),
    ("Rockwell Automation", "Large sponsor", "Industrial", "rockwellautomation", "wd1", "External"),
    ("John Deere", "Large sponsor", "Industrial", "deere", "wd1", "External"),
    ("Caterpillar", "Large sponsor", "Industrial", "caterpillar", "wd5", "CaterpillarCareers"),
    ("3M", "Large sponsor", "Industrial", "3m", "wd1", "Search"),
    ("Cummins", "Large sponsor", "Industrial", "cummins", "wd1", "External"),
    ("Nike", "Large sponsor", "Retail / Tech", "nike", "wd1", "nike"),
    ("Starbucks", "Large sponsor", "Retail / Tech", "starbucks", "wd1", "External"),
    ("Costco", "Large sponsor", "Retail / Tech", "costco", "wd5", "CostcoExternal"),
    ("Walmart", "Top 25 sponsor", "Retail / Tech", "walmart", "wd5", "WalmartExternal"),
    ("Chewy", "Active sponsor", "E-commerce", "chewy", "wd1", "chewycareers"),
    ("Wayfair", "Active sponsor", "E-commerce", "wayfair", "wd1", "WayfairCareers"),
    ("FedEx", "Large sponsor", "Logistics", "fedex", "wd1", "fedexcareers"),
    ("UPS", "Large sponsor", "Logistics", "ups", "wd5", "UPSJobs"),
    ("Delta Air Lines", "Large sponsor", "Airlines", "delta", "wd1", "Delta_Careers"),
    ("United Airlines", "Large sponsor", "Airlines", "united", "wd1", "United_Careers"),
    ("Marriott International", "Large sponsor", "Hospitality", "marriott", "wd1", "MarriottCareers"),
    ("ADP", "Large sponsor", "HR Tech", "adp", "wd5", "ADP_Careers"),
    ("Nielsen", "Large sponsor", "Data / Analytics", "nielsen", "wd1", "External"),
    ("EPAM Systems", "Large sponsor", "IT Services", "epam", "wd1", "EPAM_Careers"),
    ("Genpact", "Large sponsor", "IT Services", "genpact", "wd1", "Genpact_Careers"),
    ("Thoughtworks", "Large sponsor", "IT Services", "thoughtworks", "wd3", "Thoughtworks"),
    ("DoorDash", "Active sponsor", "Marketplace", "doordash", "wd5", "DoorDashExternal"),
    ("Zoom", "Large sponsor", "Communications", "zoom", "wd5", "Zoom"),
    ("Unity", "Active sponsor", "Gaming", "unity", "wd1", "External"),
    ("Electronic Arts", "Active sponsor", "Gaming", "ea", "wd1", "ea"),
    ("Netflix", "Large sponsor", "Media", "netflix", "wd1", "Netflix"),
    ("Roku", "Active sponsor", "Media", "roku", "wd1", "Roku_Careers"),
    ("Atlassian", "Active sponsor", "Dev Tools", "atlassian", "wd3", "External"),
    ("Shopify", "Active sponsor", "E-commerce", "shopify", "wd3", "External"),
    ("Snap", "Active sponsor", "Social", "snap", "wd1", "snap"),
    ("Toast", "Active sponsor", "Fintech", "toast", "wd5", "Toast"),
    ("SoFi", "Active sponsor", "Fintech", "sofi", "wd12", "SoFi"),
    ("Tenable", "Active sponsor", "Security", "tenable", "wd1", "Tenable"),
    ("Rapid7", "Active sponsor", "Security", "rapid7", "wd5", "Rapid7"),
    ("Netskope", "Active sponsor", "Security", "netskope", "wd1", "Netskope"),
    ("Fastly", "Active sponsor", "CDN", "fastly", "wd1", "Fastly"),
    ("DigitalOcean", "Active sponsor", "Cloud", "digitalocean", "wd1", "DigitalOcean"),
    ("Illumio", "Active sponsor", "Security", "illumio", "wd1", "Illumio"),
]
